WAD_CW2_00002399.Web/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WAD_CW2_00002399.Web.Controllers
{
    public class ContactsController : BaseController
    {
        // GET: Contacts
        public ActionResult Index()
        {
            return View();
        }
    }
}

WAD_CW2_00002399.Web/Controllers/SupportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using WAD_CW2_00002399.Core.Services;
using WAD_CW2_00002399.Web.Mappers;
using WAD_CW2_00002399.Web.Models;

namespace WAD_CW2_00002399.Web.Controllers
{
    public class SupportController : BaseController
    {
        //static properties does not requiere instantiation on accessing different Actions
        static IQuestionsService _questionService;

        //singleton to ensure that there is only one instance of the service
        private IQuestionsService questionService
        {
            get
            {
                if (_questionService == null)
                    _questionService = new QuestionsDBService();
                return _questionService;
            }
        }
        // GET: Support
        public ActionResult Index()
        {
            var model = new QuestionViewModel();
            ViewBag.Category = new SelectList(questionService.GetQuestionCats(), "Id", "Name", 1);
            return View();
        }

        [HttpPost]
        public ActionResult Index(QuestionViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var question = QuestionMapper.MapQuestionsFromModel(model);
                    questionService.Insert(question);
                    ViewBag.Category = new SelectList(questionService.GetQuestionCats(), "id", "name", model.Id);
                    var cat = question.QuestionCategory.Name;

                    var Smtp = new SmtpClient("smtp.mail.ru", 25);
                    Smtp.Credentials = new NetworkCredential("00002399@mail.ru", "chunga-changa"); //lets say this is mail server
                    Smtp.EnableSsl = true;

                    //Message formating
                    System.Net.Mail.MailMessage Message = new System.Net.Mail.MailMessage();
                    //From 
                    Message.From = new MailAddress("00002399@mail.ru");//email from should be equal to the mail server
                    //To
                    Message.To.Add(new MailAddress("supprts.mail.address@mail.ru"));//mail address will be sent to support stuff's mail
                    Message.Subject = "Subject: " + cat;
                    string message = "From: " + model.Email + " ";
                    message = message + "\n";

                    message = message + "User name: " + model.Name;

                    message = message + "\n";

                    message = message + "Question: " + "\n" + model.Question;

                    Message.Body = message;

                    Smtp.Send(Message);//sending

                    ViewBag.successMessage = "Thank you for your question! The support staff will connect with you soon.";
                }
                catch (Exception e)
                {
                    ViewBag.successMessage = "An error has occured. Please try again later " + e.Message;
                }
            }
            else
            {
                throw new Exception("Хакер ака пожалуйста введите значиния в поля. Я тут 15 часов без перерыва вожусь с валидейшоном. До questionViewModel не доходит и никакой validation не срабатывает и передает null значения ((( и сейчас 3 часа ночи");
            }
            return View(model);
        }
    }
}

WAD_CW2_00002399.Web/Controllers/UserController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WAD_CW2_00002399.Core.Entities;
using WAD_CW2_00002399.Core.Services;
using WAD_CW2_00002399.Web.Helpers;
using WAD_CW2_00002399.Web.Models;

namespace WAD_CW2_00002399.Web.Controllers
{
    public class UserController : BaseController
    {
        static UserService _userService = new UserService();

        // GET: User/Login
        public ActionResult Login()
        {
            return View();
        }

        // POST: User/Login
        [HttpPost]
        public ActionResult Login(LoginViewModel loginVM)
        {
            if (!ModelState.IsValid)
                return View(loginVM);
            try
            {
                var curUser = new Users
                {
                    Username_db = loginVM.UserName,
                    Password_db = loginVM.Password
                };
                if (_userService.Authenticate(curUser).HasValue)
                { 
                    //FormsAuthentication.SetAuthCookie(curUser.Username_db, true);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid credentials");
                    return View(loginVM);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(loginVM);
            }
        }

        //public ActionResult LogOut()
        //{
        //    FormsAuthentication.SignOut();
        //    return RedirectToAction("Index", "Home");
        //}

        // GET: User/Register
        public ActionResult Registration()
        {
            return View();
        }

        // POST: User/Register
        [HttpPost]
        public ActionResult Registration(RegViewModel registrationVM)
        {
            if (!ModelState.IsValid)
                return View(registrationVM);
            var valid = ValidateCaptcha();
            if (!valid)
            {
                ViewBag.Message = "Invalid Capture";
                return View();
            }
            try
            {
                var curUser = new Users
                {
                    Username_db = registrationVM.UserName,
                    FirstName_db = registrationVM.FirstName,
                    LastName_db = registrationVM.LastName,
                    Address_db = registrationVM.Address,
                    Password_db = registrationVM.Password,
                    Email_db = registrationVM.Email
                };
                _userService.Register(curUser);
                return RedirectToAction("Login");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(registrationVM);
            }
        }

        public ActionResult Administration()
        {
            return View();
        }

        private Boolean ValidateCaptcha()
        {
            var response = Request["g-recaptcha-response"];
            //secret that was generated in key value pair
            string secret = ConfigurationManager.AppSettings["reCAPTCHASecretKey"];
            var client = new WebClient();
            var reply =
                client.DownloadString(
                    string.Format("https://www.google.com/recaptcha/api/siteverify?secret={0}&response={1}", secret, response));
            var captchaResponse = JsonConvert.DeserializeObject<CaptchaResponse>(reply);
            //when response is false check for the error message
            if (!captchaResponse.Success)
            {
                if (captchaResponse.ErrorCodes.Count <= 0) return false;
                var error = captchaResponse.ErrorCodes[0].ToLower();
                switch (error)
                {
                    case ("missing-input-secret"):
                        ViewBag.message = "The secret parameter is missing.";
                        break;
                    case ("invalid-input-secret"):
                        ViewBag.message = "The secret parameter is invalid or malformed.";
                        break;
                    case ("missing-input-response"):
                        ViewBag.message = "The response parameter is missing. Please, preceed with reCAPTCHA.";
                        break;
                    case ("invalid-input-response"):
                        ViewBag.message = "The response parameter is invalid or malformed.";
                        break;
                    default:
                        ViewBag.message = "Error occured. Please try again";
                        break;
                }
                return false;
            }
            ViewBag.message = "Valid";
            return true;
        }
    }

}

WAD_CW2_00002399.Web/Controllers/WebServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WAD_CW2_00002399.Web.Controllers
{
    public class WebServiceController : BaseController
    {
        // GET: WebService
        public ActionResult Index()
        {
            return View();
        }
    }
}

WAD_CW2_00002399.Web/Views/Shared/_Layout.cshtml
@using Resources
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-site-verification" content="G8bD_6dXeSxPM3CLw9nqZERg5-PiIcI0k9KTRMcTuvw" />
    <link href="@Url.Content("~/Content/Styles/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Styles/bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Styles/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/JS/jquery-1.12.0.min.js")"></script>
    <script src='https://www.google.com/recaptcha/api.js' async defer></script>

</head>
<body>
    <div id="fb-root"></div>
    <script>
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ru_RU/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

    <div class="navbar navbar-inverse navbar-fixed-top ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Avtech.uz", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(@Index.Home, "Index", "Home")</li>
                    <li>@Html.ActionLink(@Index.Catalog, "Catalog", "Product")</li>
                    <li>@Html.ActionLink(@Index.BackEnd, "Index", "Product")</li>
                    <li>@Html.ActionLink(@Index.Contact, "Index", "Support")</li>
                    <li>@Html.ActionLink(@Index.WebServices, "Index", "WebService")</li>
                    <li>@Html.ActionLink(@Index.Contact2, "Index", "Contacts")</li>
                    <li>@Html.ActionLink(@Index.Login, "Login", "User")</li>
                    <li>@Html.ActionLink(@Index.Registration, "Registration", "User")</li>
                    <li><a href="@Url.Action(ViewContext.Controller.ControllerContext.RouteData.Values["action"].ToString(), ViewContext.Controller.ControllerContext.RouteData.Values["controller"].ToString(), new { Culture = "en-US" })">Eng</a></li>
                    <li><a href="@Url.Action(ViewContext.Controller.ControllerContext.RouteData.Values["action"].ToString(), ViewContext.Controller.ControllerContext.RouteData.Values["controller"].ToString(), new { Culture = "ru" })">Rus</a></li>
                    

                </ul>
            </div>
        </div>
    </div>
    <div><script>
  (function() {
    var cx = '012594685179108708905:defidcneqvu';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
        '//cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:search></gcse:search></div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="fb-like" data-href="http://s00002399-001-site1.btempurl.com/" data-width="500" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>

            <script type="text/javascript">
sa_client = "2a17578d50968e2ec6b6aa9d92d1ac87";
sa_code = "86bfc344ead16cd957d5af0316f2804f";
sa_protocol = ("https:"==document.location.protocol)?"https":"http";
sa_pline = "0";
sa_maxads = "4";
sa_bgcolor = "FFFFFF";
sa_bordercolor = "3EBEF3";
sa_superbordercolor = "3EBEF3";
sa_linkcolor = "001EB5";
sa_desccolor = "000000";
sa_urlcolor = "005677";
sa_b = "0";
sa_format = "banner_728x90_4";
sa_width = "728";
sa_height = "90";
sa_location = "0";
sa_radius = "0";
sa_borderwidth = "1";
sa_font = "0";
document.write(unescape("%3cscript type='text/javascript' src='"+sa_protocol+"://sa.entireweb.com/sense2.js'%3e%3c/script%3e"));
            </script>
            <p>00002399 - All rights reserved- &copy; @DateTime.Now.Year</p>
            <a href="http://validator.w3.org/check?uri=referer"><img style="border:0;width:88px;height:31px" src="http://www.w3.org/Icons/valid-xhtml10" alt="Valid XHTML 1.0 Transitional" width="88" height="31" vspace="8" border="0" /></a>
            <a href="http://jigsaw.w3.org/css-validator/check/referer"><img style="border:0;width:88px;height:31px" src="http://jigsaw.w3.org/css-validator/images/vcss-blue" alt="Valid CSS!" vspace="8" border="0" /></a>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-75411107-1', 'auto');
  ga('send', 'pageview');

</script>